### ISSUE TITLE
Different country should not have changed my vm size

### ISSUE THREAD

**Issue by henriquebrisola** [kvaes/azure-vmchooser-docs#1]
I was using the bulk uploader for 3 datacenters, one at a time.
I used the following setup on the vmchooser.csv file:

VM Name | Region | Cores | Memory (GB) | SSD | NICs | Max Disk Size (TB) | IOPS | Throughput (MB/s) | Min Temp Disk Size (GB) | Peak CPU Usage (%) | Peak Memory Usage (%) | Currency | Contract | Burstable | SAPHANA | SAPS2T | SAPS3T | SISLA | OVERRIDEDISKTYPE | OS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DXDCWZH01 | brazil-south | 4 | 16 | Yes | 1 | 0.195313 | 0 | 0 | 0 | 50 | 75 | USD | payg | No |   |   |   |   | standardssd | linux
DXDCWZH01 | east-us | 4 | 16 | Yes | 1 | 0.195313 | 0 | 0 | 0 | 50 | 75 | USD | payg | No |   |   |   |   | standardssd | linux

However for Brazil the output was a 'ds11' vm and for US East the output was 'e2sv3'.
After further analysis I see no reason for that. theses option are available on both regions, there are no limitations.

Btw, in this scenario the 'e2sv3' vm is much better than 'ds11', because is cheaper, faster and has 16gb of ram rather than 14gb of the latter.

This is an example, there are more VMs with this inconsistencies.
Just noticed, there is no DS11 vm on Azure for Brazil, neither D11S, the options are: D11, D11v2, DS11-1v2 and DS11v2.

**Comment by kvaes** [comment]
Only just noticed your issue... #oops
I only monitor the front-end one ; https://github.com/kvaes/azure-vmchooser-frontend-v3/issues

This is "expected behaviour", where VMchooser will pick the cheapest option available. It might be that another DC has a different pricing effect.
